services:
  minimal-api:
    image: akoscontainers/dtestapi:latest
    container_name: minimal-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DT_LOGLEVEL=info
    ports:
      - "8080:8080"
    depends_on:
      - dynatrace-oneagent
    volumes:
      - /opt/dynatrace/oneagent:/opt/dynatrace/oneagent

  dynatrace-oneagent:
    image: "dynatrace/oneagent"
    container_name: dynatrace-oneagent
    environment:
      - ONEAGENT_INSTALLER_SCRIPT_URL=ValueOfEnv
      - ONEAGENT_INSTALLER_SCRIPT_ARGS=--set-host-group=production
      - ONEAGENT_INSTALLER_DOWNLOAD_TOKEN=ValueOfEnv
    privileged: true
    pid: "host"
    network_mode: "host"
    volumes:
      - /:/mnt/root
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/dynatrace:/var/log/dynatrace
      - /var/lib/dynatrace/oneagent:/var/lib/dynatrace/oneagent
      - /var/lib/dynatrace/enrichment:/var/lib/dynatrace/enrichment
